// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_BLOCK_SIDESHAPETYPE$3_HPP
#define NET_MINECRAFT_BLOCK_SIDESHAPETYPE$3_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.block.SideShapeType$3
 * Remapped: doa$3
 */
namespace SideShapeType$3 {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("doa$3", "net/minecraft/world/level/block/SupportType$3", "net/minecraft/class_5431$3", "net/minecraft/block/SideShapeType$3", "net/minecraft/src/C_1931_$C_1934_"));
        }
        return cachedClass;
    };

    // getter for private field net.minecraft.block.SideShapeType$3#ringWidth
    static jint get_field_ringWidth(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("d", "RIGID_SUPPORT_WIDTH", "field_25828", "ringWidth", "f_57234_"), "I");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetIntField(obj, fieldID);
    };

    // setter for static private field net.minecraft.block.SideShapeType$3#ringWidth
    static void set_field_ringWidth(const jobject &obj, const jint &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("d", "RIGID_SUPPORT_WIDTH", "field_25828", "ringWidth", "f_57234_"), "I");
        return MinecraftSDK::env->SetIntField(obj, fieldID, value);
    };

    // getter for private field net.minecraft.block.SideShapeType$3#hollowSquareCuboid
    static jobject get_field_hollowSquareCuboid(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("e", "RIGID_SUPPORT_SHAPE", "field_25829", "hollowSquareCuboid", "f_57235_"), "Lexv;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.block.SideShapeType$3#hollowSquareCuboid
    static void set_field_hollowSquareCuboid(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("e", "RIGID_SUPPORT_SHAPE", "field_25829", "hollowSquareCuboid", "f_57235_"), "Lexv;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    static jmethodID methodID_matches() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "isSupporting", "method_30367", "matches", "m_5588_"), "(Ldtc;Ldcc;Ljd;Lji;)Z");
    }

    static jboolean matches(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3) {
                
       const auto methodID = methodID_matches();
       return MinecraftSDK::env->CallBooleanMethod(obj, methodID, arg0, arg1, arg2, arg3);
    };
    
};

#endif // NET_MINECRAFT_BLOCK_SIDESHAPETYPE$3_HPP