// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_CLIENT_GUI_TOOLTIP_TOOLTIPPOSITIONER_HPP
#define NET_MINECRAFT_CLIENT_GUI_TOOLTIP_TOOLTIPPOSITIONER_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.client.gui.tooltip.TooltipPositioner
 * Remapped: fqo
 */
namespace TooltipPositioner {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("fqo", "net/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipPositioner", "net/minecraft/class_8000", "net/minecraft/client/gui/tooltip/TooltipPositioner", "net/minecraft/src/C_262719_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_getPosition() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "positionTooltip", "method_47944", "getPosition", "m_262814_"), "(IIIIII)Lorg/joml/Vector2ic;");
    }

    static jobject getPosition(const jobject& obj, const jint& arg0, const jint& arg1, const jint& arg2, const jint& arg3, const jint& arg4, const jint& arg5) {
                
       const auto methodID = methodID_getPosition();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1, arg2, arg3, arg4, arg5);
    };
    
};

#endif // NET_MINECRAFT_CLIENT_GUI_TOOLTIP_TOOLTIPPOSITIONER_HPP