// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_BLOCK_ENTITY_ENDPORTALBLOCKENTITY_HPP
#define NET_MINECRAFT_BLOCK_ENTITY_ENDPORTALBLOCKENTITY_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.block.entity.EndPortalBlockEntity
 * Remapped: drz
 */
namespace EndPortalBlockEntity {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("drz", "net/minecraft/world/level/block/entity/TheEndPortalBlockEntity", "net/minecraft/class_2640", "net/minecraft/block/entity/EndPortalBlockEntity", "net/minecraft/src/C_2033_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_shouldDrawSide() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "shouldRenderFace", "method_11400", "shouldDrawSide", "m_6665_"), "(Lji;)Z");
    }

    static jboolean shouldDrawSide(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_shouldDrawSide();
       return MinecraftSDK::env->CallBooleanMethod(obj, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_BLOCK_ENTITY_ENDPORTALBLOCKENTITY_HPP