// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_STRUCTURE_STRUCTURETEMPLATE_HPP
#define NET_MINECRAFT_STRUCTURE_STRUCTURETEMPLATE_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.structure.StructureTemplate
 * Remapped: ent
 */
namespace StructureTemplate {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("ent", "net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplate", "net/minecraft/class_3499", "net/minecraft/structure/StructureTemplate", "net/minecraft/src/C_2634_"));
        }
        return cachedClass;
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#PALETTE_KEY
    [[maybe_unused]] static jobject get_field_PALETTE_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("a", "PALETTE_TAG", "field_31687", "PALETTE_KEY", "f_163789_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#PALETTE_KEY
    [[maybe_unused]] static void set_field_PALETTE_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("a", "PALETTE_TAG", "field_31687", "PALETTE_KEY", "f_163789_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#PALETTES_KEY
    [[maybe_unused]] static jobject get_field_PALETTES_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("b", "PALETTE_LIST_TAG", "field_31688", "PALETTES_KEY", "f_163790_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#PALETTES_KEY
    [[maybe_unused]] static void set_field_PALETTES_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("b", "PALETTE_LIST_TAG", "field_31688", "PALETTES_KEY", "f_163790_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#ENTITIES_KEY
    [[maybe_unused]] static jobject get_field_ENTITIES_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("c", "ENTITIES_TAG", "field_31689", "ENTITIES_KEY", "f_163791_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#ENTITIES_KEY
    [[maybe_unused]] static void set_field_ENTITIES_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("c", "ENTITIES_TAG", "field_31689", "ENTITIES_KEY", "f_163791_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#BLOCKS_KEY
    [[maybe_unused]] static jobject get_field_BLOCKS_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("d", "BLOCKS_TAG", "field_31690", "BLOCKS_KEY", "f_163792_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#BLOCKS_KEY
    [[maybe_unused]] static void set_field_BLOCKS_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("d", "BLOCKS_TAG", "field_31690", "BLOCKS_KEY", "f_163792_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#BLOCKS_POS_KEY
    [[maybe_unused]] static jobject get_field_BLOCKS_POS_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("e", "BLOCK_TAG_POS", "field_31691", "BLOCKS_POS_KEY", "f_163793_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#BLOCKS_POS_KEY
    [[maybe_unused]] static void set_field_BLOCKS_POS_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("e", "BLOCK_TAG_POS", "field_31691", "BLOCKS_POS_KEY", "f_163793_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#BLOCKS_STATE_KEY
    [[maybe_unused]] static jobject get_field_BLOCKS_STATE_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("f", "BLOCK_TAG_STATE", "field_31692", "BLOCKS_STATE_KEY", "f_163794_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#BLOCKS_STATE_KEY
    [[maybe_unused]] static void set_field_BLOCKS_STATE_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("f", "BLOCK_TAG_STATE", "field_31692", "BLOCKS_STATE_KEY", "f_163794_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#BLOCKS_NBT_KEY
    [[maybe_unused]] static jobject get_field_BLOCKS_NBT_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("g", "BLOCK_TAG_NBT", "field_31693", "BLOCKS_NBT_KEY", "f_163795_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#BLOCKS_NBT_KEY
    [[maybe_unused]] static void set_field_BLOCKS_NBT_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("g", "BLOCK_TAG_NBT", "field_31693", "BLOCKS_NBT_KEY", "f_163795_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#ENTITIES_POS_KEY
    [[maybe_unused]] static jobject get_field_ENTITIES_POS_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("h", "ENTITY_TAG_POS", "field_31694", "ENTITIES_POS_KEY", "f_163796_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#ENTITIES_POS_KEY
    [[maybe_unused]] static void set_field_ENTITIES_POS_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("h", "ENTITY_TAG_POS", "field_31694", "ENTITIES_POS_KEY", "f_163796_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#ENTITIES_BLOCK_POS_KEY
    [[maybe_unused]] static jobject get_field_ENTITIES_BLOCK_POS_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("i", "ENTITY_TAG_BLOCKPOS", "field_31695", "ENTITIES_BLOCK_POS_KEY", "f_163797_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#ENTITIES_BLOCK_POS_KEY
    [[maybe_unused]] static void set_field_ENTITIES_BLOCK_POS_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("i", "ENTITY_TAG_BLOCKPOS", "field_31695", "ENTITIES_BLOCK_POS_KEY", "f_163797_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#ENTITIES_NBT_KEY
    [[maybe_unused]] static jobject get_field_ENTITIES_NBT_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("j", "ENTITY_TAG_NBT", "field_31696", "ENTITIES_NBT_KEY", "f_163798_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#ENTITIES_NBT_KEY
    [[maybe_unused]] static void set_field_ENTITIES_NBT_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("j", "ENTITY_TAG_NBT", "field_31696", "ENTITIES_NBT_KEY", "f_163798_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.structure.StructureTemplate#SIZE_KEY
    [[maybe_unused]] static jobject get_field_SIZE_KEY() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("k", "SIZE_TAG", "field_31697", "SIZE_KEY", "f_163799_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.structure.StructureTemplate#SIZE_KEY
    [[maybe_unused]] static void set_field_SIZE_KEY(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("k", "SIZE_TAG", "field_31697", "SIZE_KEY", "f_163799_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for private field net.minecraft.structure.StructureTemplate#blockInfoLists
    static jobject get_field_blockInfoLists(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("l", "palettes", "field_15586", "blockInfoLists", "f_74482_"), "Ljava/util/List;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.structure.StructureTemplate#blockInfoLists
    static void set_field_blockInfoLists(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("l", "palettes", "field_15586", "blockInfoLists", "f_74482_"), "Ljava/util/List;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    // getter for private field net.minecraft.structure.StructureTemplate#entities
    static jobject get_field_entities(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("m", "entityInfoList", "field_15589", "entities", "f_74483_"), "Ljava/util/List;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.structure.StructureTemplate#entities
    static void set_field_entities(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("m", "entityInfoList", "field_15589", "entities", "f_74483_"), "Ljava/util/List;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    // getter for private field net.minecraft.structure.StructureTemplate#size
    static jobject get_field_size(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("n", "size", "field_15587", "size", "f_74484_"), "Lkh;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.structure.StructureTemplate#size
    static void set_field_size(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("n", "size", "field_15587", "size", "f_74484_"), "Lkh;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    // getter for private field net.minecraft.structure.StructureTemplate#author
    static jobject get_field_author(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("o", "author", "field_15588", "author", "f_74485_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.structure.StructureTemplate#author
    static void set_field_author(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("o", "author", "field_15588", "author", "f_74485_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    static jmethodID methodID_getSize() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getSize", "method_15160", "getSize", "m_163801_"), "()Lkh;");
    }

    static jobject getSize(const jobject& obj) {
                
       const auto methodID = methodID_getSize();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID);
    };
    
    static jmethodID methodID_setAuthor() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "setAuthor", "method_15161", "setAuthor", "m_74612_"), "(Ljava/lang/String;)V");
    }

    static void setAuthor(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_setAuthor();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0);
    };
    
    static jmethodID methodID_getAuthor() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("b", "getAuthor", "method_15181", "getAuthor", "m_74627_"), "()Ljava/lang/String;");
    }

    static jobject getAuthor(const jobject& obj) {
                
       const auto methodID = methodID_getAuthor();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID);
    };
    
    static jmethodID methodID_saveFromWorld() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "fillFromWorld", "method_15174", "saveFromWorld", "m_163802_"), "(Ldcw;Ljd;Lkh;ZLdfy;)V");
    }

    static void saveFromWorld(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2, const jboolean& arg3, const jobject& arg4) {
                
       const auto methodID = methodID_saveFromWorld();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2, arg3, arg4);
    };
    
    static jmethodID methodID_categorize() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "addToLists", "method_28054", "categorize", "m_74573_"), "(Lent$c;Ljava/util/List;Ljava/util/List;Ljava/util/List;)V");
    }

    static void categorize(const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID_categorize();
       MinecraftSDK::env->CallStaticVoidMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_combineSorted() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "buildInfoList", "method_28055", "combineSorted", "m_74614_"), "(Ljava/util/List;Ljava/util/List;Ljava/util/List;)Ljava/util/List;");
    }

    static jobject combineSorted(const jobject& arg0, const jobject& arg1, const jobject& arg2) {
       const auto clazz = self();
       const auto methodID = methodID_combineSorted();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2);
    };
    
    static jmethodID methodID_addEntitiesFromWorld() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "fillEntityList", "method_15164", "addEntitiesFromWorld", "m_74500_"), "(Ldcw;Ljd;Ljd;)V");
    }

    static void addEntitiesFromWorld(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2) {
                
       const auto methodID = methodID_addEntitiesFromWorld();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2);
    };
    
    static jmethodID methodID_getInfosForBlock() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "filterBlocks", "method_16445", "getInfosForBlock", "m_74603_"), "(Ljd;Lenp;Ldfy;)Ljava/util/List;");
    }

    static jobject getInfosForBlock(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2) {
                
       const auto methodID = methodID_getInfosForBlock();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1, arg2);
    };
    
    static jmethodID methodID__getInfosForBlock() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "filterBlocks", "method_15165", "getInfosForBlock", "m_230335_"), "(Ljd;Lenp;Ldfy;Z)Lit/unimi/dsi/fastutil/objects/ObjectArrayList;");
    }

    static jobject _getInfosForBlock(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2, const jboolean& arg3) {
                
       const auto methodID = methodID__getInfosForBlock();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_transformBox() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "calculateConnectedPosition", "method_15180", "transformBox", "m_74566_"), "(Lenp;Ljd;Lenp;Ljd;)Ljd;");
    }

    static jobject transformBox(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3) {
                
       const auto methodID = methodID_transformBox();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_transform() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "calculateRelativePosition", "method_15171", "transform", "m_74563_"), "(Lenp;Ljd;)Ljd;");
    }

    static jobject transform(const jobject& arg0, const jobject& arg1) {
       const auto clazz = self();
       const auto methodID = methodID_transform();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_place() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "placeInWorld", "method_15172", "place", "m_230328_"), "(Lddl;Ljd;Ljd;Lenp;Layw;I)Z");
    }

    static jboolean place(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3, const jobject& arg4, const jint& arg5) {
                
       const auto methodID = methodID_place();
       return MinecraftSDK::env->CallBooleanMethod(obj, methodID, arg0, arg1, arg2, arg3, arg4, arg5);
    };
    
    static jmethodID methodID_updateCorner() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "updateShapeAtEdge", "method_58190", "updateCorner", "m_324019_"), "(Ldcx;ILexl;Ljd;)V");
    }

    static void updateCorner(const jobject& arg0, const jint& arg1, const jobject& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID_updateCorner();
       MinecraftSDK::env->CallStaticVoidMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID__updateCorner() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "updateShapeAtEdge", "method_20532", "updateCorner", "m_74510_"), "(Ldcx;ILexl;III)V");
    }

    static void _updateCorner(const jobject& arg0, const jint& arg1, const jobject& arg2, const jint& arg3, const jint& arg4, const jint& arg5) {
       const auto clazz = self();
       const auto methodID = methodID__updateCorner();
       MinecraftSDK::env->CallStaticVoidMethod(clazz, methodID, arg0, arg1, arg2, arg3, arg4, arg5);
    };
    
    static jmethodID methodID_process() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "processBlockInfos", "method_16446", "process", "m_74517_"), "(Lddl;Ljd;Ljd;Lenp;Ljava/util/List;)Ljava/util/List;");
    }

    static jobject process(const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3, const jobject& arg4) {
       const auto clazz = self();
       const auto methodID = methodID_process();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3, arg4);
    };
    
    static jmethodID methodID_spawnEntities() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "placeEntities", "method_15179", "spawnEntities", "m_74523_"), "(Lddl;Ljd;Ldkv;Ldmm;Ljd;Lejj;Z)V");
    }

    static void spawnEntities(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3, const jobject& arg4, const jobject& arg5, const jboolean& arg6) {
                
       const auto methodID = methodID_spawnEntities();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2, arg3, arg4, arg5, arg6);
    };
    
    static jmethodID methodID_getEntity() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "createEntityIgnoreException", "method_17916", "getEntity", "m_74543_"), "(Lddl;Lub;)Ljava/util/Optional;");
    }

    static jobject getEntity(const jobject& arg0, const jobject& arg1) {
       const auto clazz = self();
       const auto methodID = methodID_getEntity();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_getRotatedSize() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getSize", "method_15166", "getRotatedSize", "m_163808_"), "(Ldmm;)Lkh;");
    }

    static jobject getRotatedSize(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_getRotatedSize();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0);
    };
    
    static jmethodID methodID_transformAround() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "transform", "method_15168", "transformAround", "m_74593_"), "(Ljd;Ldkv;Ldmm;Ljd;)Ljd;");
    }

    static jobject transformAround(const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID_transformAround();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID__transformAround() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "transform", "method_15176", "transformAround", "m_74578_"), "(Lexc;Ldkv;Ldmm;Ljd;)Lexc;");
    }

    static jobject _transformAround(const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID__transformAround();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_offsetByTransformedSize() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getZeroPositionWithTransform", "method_15167", "offsetByTransformedSize", "m_74583_"), "(Ljd;Ldkv;Ldmm;)Ljd;");
    }

    static jobject offsetByTransformedSize(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2) {
                
       const auto methodID = methodID_offsetByTransformedSize();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1, arg2);
    };
    
    static jmethodID methodID_applyTransformedOffset() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "getZeroPositionWithTransform", "method_15162", "applyTransformedOffset", "m_74587_"), "(Ljd;Ldkv;Ldmm;II)Ljd;");
    }

    static jobject applyTransformedOffset(const jobject& arg0, const jobject& arg1, const jobject& arg2, const jint& arg3, const jint& arg4) {
       const auto clazz = self();
       const auto methodID = methodID_applyTransformedOffset();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3, arg4);
    };
    
    static jmethodID methodID_calculateBoundingBox() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("b", "getBoundingBox", "method_16187", "calculateBoundingBox", "m_74633_"), "(Lenp;Ljd;)Lejj;");
    }

    static jobject calculateBoundingBox(const jobject& obj, const jobject& arg0, const jobject& arg1) {
                
       const auto methodID = methodID_calculateBoundingBox();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID__calculateBoundingBox() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getBoundingBox", "method_27267", "calculateBoundingBox", "m_74598_"), "(Ljd;Ldmm;Ljd;Ldkv;)Lejj;");
    }

    static jobject _calculateBoundingBox(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3) {
                
       const auto methodID = methodID__calculateBoundingBox();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_createBox() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "getBoundingBox", "method_34400", "createBox", "m_163810_"), "(Ljd;Ldmm;Ljd;Ldkv;Lkh;)Lejj;");
    }

    static jobject createBox(const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3, const jobject& arg4) {
       const auto clazz = self();
       const auto methodID = methodID_createBox();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3, arg4);
    };
    
    static jmethodID methodID_writeNbt() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "save", "method_15175", "writeNbt", "m_74618_"), "(Lub;)Lub;");
    }

    static jobject writeNbt(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_writeNbt();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0);
    };
    
    static jmethodID methodID_readNbt() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "load", "method_15183", "readNbt", "m_246595_"), "(Ljn;Lub;)V");
    }

    static void readNbt(const jobject& obj, const jobject& arg0, const jobject& arg1) {
                
       const auto methodID = methodID_readNbt();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_loadPalettedBlockInfo() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "loadPalette", "method_15177", "loadPalettedBlockInfo", "m_247272_"), "(Ljn;Luh;Luh;)V");
    }

    static void loadPalettedBlockInfo(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2) {
                
       const auto methodID = methodID_loadPalettedBlockInfo();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2);
    };
    
    static jmethodID methodID_createNbtIntList() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "newIntegerList", "method_15169", "createNbtIntList", "m_74625_"), "([I)Luh;");
    }

    static jobject createNbtIntList(const jobject& obj, const jarray& arg0, const jint& arg1) {
                
       const auto methodID = methodID_createNbtIntList();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_createNbtDoubleList() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "newDoubleList", "method_15184", "createNbtDoubleList", "m_74623_"), "([D)Luh;");
    }

    static jobject createNbtDoubleList(const jobject& obj, const jarray& arg0, const jdouble& arg1) {
                
       const auto methodID = methodID_createNbtDoubleList();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1);
    };
    
};

#endif // NET_MINECRAFT_STRUCTURE_STRUCTURETEMPLATE_HPP