// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_CLIENT_TUTORIAL_TUTORIALSTEPHANDLER_HPP
#define NET_MINECRAFT_CLIENT_TUTORIAL_TUTORIALSTEPHANDLER_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.client.tutorial.TutorialStepHandler
 * Remapped: gwj
 */
namespace TutorialStepHandler {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("gwj", "net/minecraft/client/tutorial/TutorialStepInstance", "net/minecraft/class_1155", "net/minecraft/client/tutorial/TutorialStepHandler", "net/minecraft/src/C_4620_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_destroy() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("b", "clear", "method_4902", "destroy", "m_7736_"), "()V");
    }

    static void destroy(const jobject& obj) {
                
       const auto methodID = methodID_destroy();
       MinecraftSDK::env->CallVoidMethod(obj, methodID);
    };
    
    static jmethodID methodID_tick() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "tick", "method_4899", "tick", "m_7737_"), "()V");
    }

    static void tick(const jobject& obj) {
                
       const auto methodID = methodID_tick();
       MinecraftSDK::env->CallVoidMethod(obj, methodID);
    };
    
    static jmethodID methodID_onMovement() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "onInput", "method_4903", "onMovement", "m_6484_"), "(Lgdz;)V");
    }

    static void onMovement(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_onMovement();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0);
    };
    
    static jmethodID methodID_onMouseUpdate() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "onMouse", "method_4901", "onMouseUpdate", "m_6420_"), "(DD)V");
    }

    static void onMouseUpdate(const jobject& obj, const jdouble& arg0, const jdouble& arg1) {
                
       const auto methodID = methodID_onMouseUpdate();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_onTarget() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "onLookAt", "method_4898", "onTarget", "m_7554_"), "(Lfzf;Lexa;)V");
    }

    static void onTarget(const jobject& obj, const jobject& arg0, const jobject& arg1) {
                
       const auto methodID = methodID_onTarget();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_onBlockBreaking() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "onDestroyBlock", "method_4900", "onBlockBreaking", "m_7464_"), "(Lfzf;Ljd;Ldtc;F)V");
    }

    static void onBlockBreaking(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2, const jfloat& arg3) {
                
       const auto methodID = methodID_onBlockBreaking();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_onInventoryOpened() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("c", "onOpenInventory", "method_4904", "onInventoryOpened", "m_7744_"), "()V");
    }

    static void onInventoryOpened(const jobject& obj) {
                
       const auto methodID = methodID_onInventoryOpened();
       MinecraftSDK::env->CallVoidMethod(obj, methodID);
    };
    
    static jmethodID methodID_onSlotUpdate() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "onGetItem", "method_4897", "onSlotUpdate", "m_6967_"), "(Lcuq;)V");
    }

    static void onSlotUpdate(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_onSlotUpdate();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_CLIENT_TUTORIAL_TUTORIALSTEPHANDLER_HPP