// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_LOOT_ENTRY_LEAFENTRY$CHOICE_HPP
#define NET_MINECRAFT_LOOT_ENTRY_LEAFENTRY$CHOICE_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.loot.entry.LeafEntry$Choice
 * Remapped: esj$c
 */
namespace LeafEntry$Choice {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("esj$c", "net/minecraft/world/level/storage/loot/entries/LootPoolSingletonContainer$EntryBase", "net/minecraft/class_85$class_88", "net/minecraft/loot/entry/LeafEntry$Choice", "net/minecraft/src/C_2860_$C_2864_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_getWeight() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getWeight", "method_427", "getWeight", "m_7067_"), "(F)I");
    }

    static jint getWeight(const jobject& obj, const jfloat& arg0) {
                
       const auto methodID = methodID_getWeight();
       return MinecraftSDK::env->CallIntMethod(obj, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_LOOT_ENTRY_LEAFENTRY$CHOICE_HPP