// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_CLIENT_PARTICLE_ENDRODPARTICLE_HPP
#define NET_MINECRAFT_CLIENT_PARTICLE_ENDRODPARTICLE_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.client.particle.EndRodParticle
 * Remapped: gbu
 */
namespace EndRodParticle {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("gbu", "net/minecraft/client/particle/EndRodParticle", "net/minecraft/class_675", "net/minecraft/client/particle/EndRodParticle", "net/minecraft/src/C_3980_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_move() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "move", "method_3069", "move", "m_6257_"), "(DDD)V");
    }

    static void move(const jobject& obj, const jdouble& arg0, const jdouble& arg1, const jdouble& arg2) {
                
       const auto methodID = methodID_move();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2);
    };
    
};

#endif // NET_MINECRAFT_CLIENT_PARTICLE_ENDRODPARTICLE_HPP