// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_ENTITY_AI_FUZZYTARGETING_HPP
#define NET_MINECRAFT_ENTITY_AI_FUZZYTARGETING_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.entity.ai.FuzzyTargeting
 * Remapped: cem
 */
namespace FuzzyTargeting {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("cem", "net/minecraft/world/entity/ai/util/LandRandomPos", "net/minecraft/class_5534", "net/minecraft/entity/ai/FuzzyTargeting", "net/minecraft/src/C_141113_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_find() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "getPos", "method_31527", "find", "m_148488_"), "(Lbtw;II)Lexc;");
    }

    static jobject find(const jobject& arg0, const jint& arg1, const jint& arg2) {
       const auto clazz = self();
       const auto methodID = methodID_find();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2);
    };
    
    static jmethodID methodID__find() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "getPos", "method_31530", "find", "m_148503_"), "(Lbtw;IILjava/util/function/ToDoubleFunction;)Lexc;");
    }

    static jobject _find(const jobject& arg0, const jint& arg1, const jint& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID__find();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_findTo() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "getPosTowards", "method_31528", "findTo", "m_148492_"), "(Lbtw;IILexc;)Lexc;");
    }

    static jobject findTo(const jobject& arg0, const jint& arg1, const jint& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID_findTo();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_findFrom() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("b", "getPosAway", "method_31534", "findFrom", "m_148521_"), "(Lbtw;IILexc;)Lexc;");
    }

    static jobject findFrom(const jobject& arg0, const jint& arg1, const jint& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID_findFrom();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_findValid() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "getPosInDirection", "method_31529", "findValid", "m_148497_"), "(Lbtw;IILexc;Z)Lexc;");
    }

    static jobject findValid(const jobject& arg0, const jint& arg1, const jint& arg2, const jobject& arg3, const jboolean& arg4) {
       const auto clazz = self();
       const auto methodID = methodID_findValid();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3, arg4);
    };
    
    static jmethodID methodID_validate() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "movePosUpOutOfSolid", "method_31533", "validate", "m_148518_"), "(Lbtw;Ljd;)Ljd;");
    }

    static jobject validate(const jobject& arg0, const jobject& arg1) {
       const auto clazz = self();
       const auto methodID = methodID_validate();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_towardTarget() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "generateRandomPosTowardDirection", "method_31532", "towardTarget", "m_148513_"), "(Lbtw;IZLjd;)Ljd;");
    }

    static jobject towardTarget(const jobject& arg0, const jint& arg1, const jboolean& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID_towardTarget();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
};

#endif // NET_MINECRAFT_ENTITY_AI_FUZZYTARGETING_HPP