// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_CLIENT_GUI_WIDGET_TEXTICONBUTTONWIDGET$ICONONLY_HPP
#define NET_MINECRAFT_CLIENT_GUI_WIDGET_TEXTICONBUTTONWIDGET$ICONONLY_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.client.gui.widget.TextIconButtonWidget$IconOnly
 * Remapped: fjr$b
 */
namespace TextIconButtonWidget$IconOnly {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("fjr$b", "net/minecraft/client/gui/components/SpriteIconButton$CenteredIcon", "net/minecraft/class_8662$class_8664", "net/minecraft/client/gui/widget/TextIconButtonWidget$IconOnly", "net/minecraft/src/C_290288_$C_290162_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_renderWidget() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("b", "renderWidget", "method_48579", "renderWidget", "m_87963_"), "(Lfhz;IIF)V");
    }

    static void renderWidget(const jobject& obj, const jobject& arg0, const jint& arg1, const jint& arg2, const jfloat& arg3) {
                
       const auto methodID = methodID_renderWidget();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_drawMessage() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "renderString", "method_48589", "drawMessage", "m_280465_"), "(Lfhz;Lfhx;I)V");
    }

    static void drawMessage(const jobject& obj, const jobject& arg0, const jobject& arg1, const jint& arg2) {
                
       const auto methodID = methodID_drawMessage();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2);
    };
    
};

#endif // NET_MINECRAFT_CLIENT_GUI_WIDGET_TEXTICONBUTTONWIDGET$ICONONLY_HPP