// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_ENTITY_PASSIVE_FOXENTITY$WORRIABLEENTITYFILTER_HPP
#define NET_MINECRAFT_ENTITY_PASSIVE_FOXENTITY$WORRIABLEENTITYFILTER_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.entity.passive.FoxEntity$WorriableEntityFilter
 * Remapped: cfo$c
 */
namespace FoxEntity$WorriableEntityFilter {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("cfo$c", "net/minecraft/world/entity/animal/Fox$FoxAlertableEntitiesSelector", "net/minecraft/class_4019$class_4022", "net/minecraft/entity/passive/FoxEntity$WorriableEntityFilter", "net/minecraft/src/C_833_$C_837_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_test() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "test", "method_18303", "test", "test"), "(Lbtn;)Z");
    }

    static jboolean test(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_test();
       return MinecraftSDK::env->CallBooleanMethod(obj, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_ENTITY_PASSIVE_FOXENTITY$WORRIABLEENTITYFILTER_HPP