// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_ENTITY_PASSIVE_LLAMAENTITY$SPITREVENGEGOAL_HPP
#define NET_MINECRAFT_ENTITY_PASSIVE_LLAMAENTITY$SPITREVENGEGOAL_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.entity.passive.LlamaEntity$SpitRevengeGoal
 * Remapped: chl$c
 */
namespace LlamaEntity$SpitRevengeGoal {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("chl$c", "net/minecraft/world/entity/animal/horse/Llama$LlamaHurtByTargetGoal", "net/minecraft/class_1501$class_1504", "net/minecraft/entity/passive/LlamaEntity$SpitRevengeGoal", "net/minecraft/src/C_930_$C_934_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_shouldContinue() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("c", "canContinueToUse", "method_6266", "shouldContinue", "m_8045_"), "()Z");
    }

    static jboolean shouldContinue(const jobject& obj) {
                
       const auto methodID = methodID_shouldContinue();
       return MinecraftSDK::env->CallBooleanMethod(obj, methodID);
    };
    
};

#endif // NET_MINECRAFT_ENTITY_PASSIVE_LLAMAENTITY$SPITREVENGEGOAL_HPP