// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_NETWORK_HANDLER_PACKETUNBUNDLER_HPP
#define NET_MINECRAFT_NETWORK_HANDLER_PACKETUNBUNDLER_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.network.handler.PacketUnbundler
 * Remapped: wc
 */
namespace PacketUnbundler {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("wc", "net/minecraft/network/PacketBundleUnpacker", "net/minecraft/class_8036", "net/minecraft/network/handler/PacketUnbundler", "net/minecraft/src/C_263633_"));
        }
        return cachedClass;
    };

    // getter for private field net.minecraft.network.handler.PacketUnbundler#bundleHandler
    static jobject get_field_bundleHandler(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("a", "bundlerInfo", "field_48535", "bundleHandler", "f_314046_"), "Lzf;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.network.handler.PacketUnbundler#bundleHandler
    static void set_field_bundleHandler(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("a", "bundlerInfo", "field_48535", "bundleHandler", "f_314046_"), "Lzf;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    static jmethodID methodID_encode() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "encode", "method_48319", "encode", "encode"), "(Lio/netty/channel/ChannelHandlerContext;Lzg;Ljava/util/List;)V");
    }

    static void encode(const jobject& obj, const jobject& arg0, const jobject& arg1, const jobject& arg2) {
                
       const auto methodID = methodID_encode();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1, arg2);
    };
    
};

#endif // NET_MINECRAFT_NETWORK_HANDLER_PACKETUNBUNDLER_HPP