// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_ENTITY_MOB_PHANTOMENTITY$PHANTOMMOVEMENTTYPE_HPP
#define NET_MINECRAFT_ENTITY_MOB_PHANTOMENTITY$PHANTOMMOVEMENTTYPE_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.entity.mob.PhantomEntity$PhantomMovementType
 * Remapped: ckf$a
 */
namespace PhantomEntity$PhantomMovementType {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("ckf$a", "net/minecraft/world/entity/monster/Phantom$AttackPhase", "net/minecraft/class_1593$class_1594", "net/minecraft/entity/mob/PhantomEntity$PhantomMovementType", "net/minecraft/src/C_1030_$C_1032_"));
        }
        return cachedClass;
    };

    // getter for static public field net.minecraft.entity.mob.PhantomEntity$PhantomMovementType#CIRCLE
    [[maybe_unused]] static jobject get_field_CIRCLE() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("a", "CIRCLE", "field_7318", "CIRCLE", "CIRCLE"), "Lckf$a;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.entity.mob.PhantomEntity$PhantomMovementType#CIRCLE
    [[maybe_unused]] static void set_field_CIRCLE(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("a", "CIRCLE", "field_7318", "CIRCLE", "CIRCLE"), "Lckf$a;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.entity.mob.PhantomEntity$PhantomMovementType#SWOOP
    [[maybe_unused]] static jobject get_field_SWOOP() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("b", "SWOOP", "field_7317", "SWOOP", "SWOOP"), "Lckf$a;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.entity.mob.PhantomEntity$PhantomMovementType#SWOOP
    [[maybe_unused]] static void set_field_SWOOP(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("b", "SWOOP", "field_7317", "SWOOP", "SWOOP"), "Lckf$a;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    static jmethodID methodID_values() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("values", "values", "values", "values", "values"), "()[Lckf$a;");
    }

    static jobject values() {
       const auto clazz = self();
       const auto methodID = methodID_values();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID);
    };
    
    static jmethodID methodID_valueOf() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("valueOf", "valueOf", "valueOf", "valueOf", "valueOf"), "(Ljava/lang/String;)Lckf$a;");
    }

    static jobject valueOf(const jobject& arg0) {
       const auto clazz = self();
       const auto methodID = methodID_valueOf();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_ENTITY_MOB_PHANTOMENTITY$PHANTOMMOVEMENTTYPE_HPP