// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_NBT_NBTIO$INVALIDUTFSKIPPINGDATAOUTPUT_HPP
#define NET_MINECRAFT_NBT_NBTIO$INVALIDUTFSKIPPINGDATAOUTPUT_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.nbt.NbtIo$InvalidUtfSkippingDataOutput
 * Remapped: uo$a
 */
namespace NbtIo$InvalidUtfSkippingDataOutput {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("uo$a", "net/minecraft/nbt/NbtIo$StringFallbackDataOutput", "net/minecraft/class_2507$class_9003", "net/minecraft/nbt/NbtIo$InvalidUtfSkippingDataOutput", "net/minecraft/src/C_4939_$C_302182_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_writeUTF() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("writeUTF", "writeUTF", "writeUTF", "writeUTF", "writeUTF"), "(Ljava/lang/String;)V");
    }

    static void writeUTF(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_writeUTF();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_NBT_NBTIO$INVALIDUTFSKIPPINGDATAOUTPUT_HPP