// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_DATA_CLIENT_VARIANTSETTING$VALUE_HPP
#define NET_MINECRAFT_DATA_CLIENT_VARIANTSETTING$VALUE_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.data.client.VariantSetting$Value
 * Remapped: nz$a
 */
namespace VariantSetting$Value {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("nz$a", "net/minecraft/data/models/blockstates/VariantProperty$Value", "net/minecraft/class_4938$class_4939", "net/minecraft/data/client/VariantSetting$Value", "net/minecraft/src/C_4817_$C_4818_"));
        }
        return cachedClass;
    };

    // getter for private field net.minecraft.data.client.VariantSetting$Value#value
    static jobject get_field_value(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("b", "value", "field_22899", "value", "f_125559_"), "Ljava/lang/Object;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.data.client.VariantSetting$Value#value
    static void set_field_value(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("b", "value", "field_22899", "value", "f_125559_"), "Ljava/lang/Object;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    static jmethodID methodID_getParent() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getKey", "method_35907", "getParent", "m_176453_"), "()Lnz;");
    }

    static jobject getParent(const jobject& obj) {
                
       const auto methodID = methodID_getParent();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID);
    };
    
    static jmethodID methodID_writeTo() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "addToVariant", "method_25838", "writeTo", "m_125563_"), "(Lcom/google/gson/JsonObject;)V");
    }

    static void writeTo(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_writeTo();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_DATA_CLIENT_VARIANTSETTING$VALUE_HPP