// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_CLIENT_REALMS_DTO_REALMSSERVERPLAYERLIST_HPP
#define NET_MINECRAFT_CLIENT_REALMS_DTO_REALMSSERVERPLAYERLIST_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.client.realms.dto.RealmsServerPlayerList
 * Remapped: fcs
 */
namespace RealmsServerPlayerList {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("fcs", "com/mojang/realmsclient/dto/RealmsServerPlayerLists", "net/minecraft/class_4881", "net/minecraft/client/realms/dto/RealmsServerPlayerList", "net/minecraft/src/C_3252_"));
        }
        return cachedClass;
    };

    // getter for static private field net.minecraft.client.realms.dto.RealmsServerPlayerList#LOGGER
    [[maybe_unused]] static jobject get_field_LOGGER() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("b", "LOGGER", "field_22628", "LOGGER", "f_87593_"), "Lorg/slf4j/Logger;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static private field net.minecraft.client.realms.dto.RealmsServerPlayerList#LOGGER
    [[maybe_unused]] static void set_field_LOGGER(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("b", "LOGGER", "field_22628", "LOGGER", "f_87593_"), "Lorg/slf4j/Logger;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for public field net.minecraft.client.realms.dto.RealmsServerPlayerList#serverIdToPlayers
    static jobject get_field_serverIdToPlayers(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("a", "servers", "field_52121", "serverIdToPlayers", "f_87592_"), "Ljava/util/Map;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static public field net.minecraft.client.realms.dto.RealmsServerPlayerList#serverIdToPlayers
    static void set_field_serverIdToPlayers(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("a", "servers", "field_52121", "serverIdToPlayers", "f_87592_"), "Ljava/util/Map;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    static jmethodID methodID_parse() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "parse", "method_25074", "parse", "m_87596_"), "(Ljava/lang/String;)Lfcs;");
    }

    static jobject parse(const jobject& arg0) {
       const auto clazz = self();
       const auto methodID = methodID_parse();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0);
    };
    
    static jmethodID methodID_parsePlayers() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "parsePlayers", "method_25073", "parsePlayers", "m_340350_"), "(Lcom/google/gson/JsonArray;)Ljava/util/List;");
    }

    static jobject parsePlayers(const jobject& arg0) {
       const auto clazz = self();
       const auto methodID = methodID_parsePlayers();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0);
    };
    
    static jmethodID methodID_get() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getProfileResultsFor", "method_60863", "get", "m_339524_"), "(J)Ljava/util/List;");
    }

    static jobject get(const jobject& obj, const jlong& arg0) {
                
       const auto methodID = methodID_get();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_CLIENT_REALMS_DTO_REALMSSERVERPLAYERLIST_HPP