// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_CLIENT_GUI_SCREEN_DOWNLOADINGTERRAINSCREEN$WORLDENTRYREASON_HPP
#define NET_MINECRAFT_CLIENT_GUI_SCREEN_DOWNLOADINGTERRAINSCREEN$WORLDENTRYREASON_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.client.gui.screen.DownloadingTerrainScreen$WorldEntryReason
 * Remapped: fob$a
 */
namespace DownloadingTerrainScreen$WorldEntryReason {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("fob$a", "net/minecraft/client/gui/screens/ReceivingLevelScreen$Reason", "net/minecraft/class_434$class_9678", "net/minecraft/client/gui/screen/DownloadingTerrainScreen$WorldEntryReason", "net/minecraft/src/C_3582_$C_313294_"));
        }
        return cachedClass;
    };

    // getter for static public field net.minecraft.client.gui.screen.DownloadingTerrainScreen$WorldEntryReason#NETHER_PORTAL
    [[maybe_unused]] static jobject get_field_NETHER_PORTAL() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("a", "NETHER_PORTAL", "field_51487", "NETHER_PORTAL", "NETHER_PORTAL"), "Lfob$a;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.client.gui.screen.DownloadingTerrainScreen$WorldEntryReason#NETHER_PORTAL
    [[maybe_unused]] static void set_field_NETHER_PORTAL(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("a", "NETHER_PORTAL", "field_51487", "NETHER_PORTAL", "NETHER_PORTAL"), "Lfob$a;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.client.gui.screen.DownloadingTerrainScreen$WorldEntryReason#END_PORTAL
    [[maybe_unused]] static jobject get_field_END_PORTAL() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("b", "END_PORTAL", "field_51488", "END_PORTAL", "END_PORTAL"), "Lfob$a;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.client.gui.screen.DownloadingTerrainScreen$WorldEntryReason#END_PORTAL
    [[maybe_unused]] static void set_field_END_PORTAL(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("b", "END_PORTAL", "field_51488", "END_PORTAL", "END_PORTAL"), "Lfob$a;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.client.gui.screen.DownloadingTerrainScreen$WorldEntryReason#OTHER
    [[maybe_unused]] static jobject get_field_OTHER() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("c", "OTHER", "field_51489", "OTHER", "OTHER"), "Lfob$a;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.client.gui.screen.DownloadingTerrainScreen$WorldEntryReason#OTHER
    [[maybe_unused]] static void set_field_OTHER(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("c", "OTHER", "field_51489", "OTHER", "OTHER"), "Lfob$a;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    static jmethodID methodID_values() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("values", "values", "values", "values", "values"), "()[Lfob$a;");
    }

    static jobject values() {
       const auto clazz = self();
       const auto methodID = methodID_values();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID);
    };
    
    static jmethodID methodID_valueOf() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("valueOf", "valueOf", "valueOf", "valueOf", "valueOf"), "(Ljava/lang/String;)Lfob$a;");
    }

    static jobject valueOf(const jobject& arg0) {
       const auto clazz = self();
       const auto methodID = methodID_valueOf();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_CLIENT_GUI_SCREEN_DOWNLOADINGTERRAINSCREEN$WORLDENTRYREASON_HPP