// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_UTIL_CRASH_CRASHREPORTSECTION_HPP
#define NET_MINECRAFT_UTIL_CRASH_CRASHREPORTSECTION_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.util.crash.CrashReportSection
 * Remapped: p
 */
namespace CrashReportSection {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("p", "net/minecraft/CrashReportCategory", "net/minecraft/class_129", "net/minecraft/util/crash/CrashReportSection", "net/minecraft/src/C_4909_"));
        }
        return cachedClass;
    };

    // getter for private field net.minecraft.util.crash.CrashReportSection#title
    static jobject get_field_title(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("a", "title", "field_1096", "title", "f_128137_"), "Ljava/lang/String;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.util.crash.CrashReportSection#title
    static void set_field_title(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("a", "title", "field_1096", "title", "f_128137_"), "Ljava/lang/String;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    // getter for private field net.minecraft.util.crash.CrashReportSection#elements
    static jobject get_field_elements(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("b", "entries", "field_1094", "elements", "f_128138_"), "Ljava/util/List;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.util.crash.CrashReportSection#elements
    static void set_field_elements(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("b", "entries", "field_1094", "elements", "f_128138_"), "Ljava/util/List;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    // getter for private field net.minecraft.util.crash.CrashReportSection#stackTrace
    static jobject get_field_stackTrace(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("c", "stackTrace", "field_1097", "stackTrace", "f_128139_"), "[Ljava/lang/StackTraceElement;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.util.crash.CrashReportSection#stackTrace
    static void set_field_stackTrace(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("c", "stackTrace", "field_1097", "stackTrace", "f_128139_"), "[Ljava/lang/StackTraceElement;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    static jmethodID methodID_createPositionString() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "formatLocation", "method_583", "createPositionString", "m_178937_"), "(Ldcy;DDD)Ljava/lang/String;");
    }

    static jobject createPositionString(const jobject& arg0, const jdouble& arg1, const jdouble& arg2, const jdouble& arg3) {
       const auto clazz = self();
       const auto methodID = methodID_createPositionString();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID__createPositionString() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "formatLocation", "method_582", "createPositionString", "m_178947_"), "(Ldcy;Ljd;)Ljava/lang/String;");
    }

    static jobject _createPositionString(const jobject& arg0, const jobject& arg1) {
       const auto clazz = self();
       const auto methodID = methodID__createPositionString();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1);
    };
    
    static jmethodID methodID___createPositionString() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "formatLocation", "method_581", "createPositionString", "m_178942_"), "(Ldcy;III)Ljava/lang/String;");
    }

    static jobject __createPositionString(const jobject& arg0, const jint& arg1, const jint& arg2, const jint& arg3) {
       const auto clazz = self();
       const auto methodID = methodID___createPositionString();
       return MinecraftSDK::env->CallStaticObjectMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
    static jmethodID methodID_add() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "setDetail", "method_577", "add", "m_128165_"), "(Ljava/lang/String;Lq;)Lp;");
    }

    static jobject add(const jobject& obj, const jobject& arg0, const jobject& arg1) {
                
       const auto methodID = methodID_add();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID__add() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "setDetail", "method_578", "add", "m_128159_"), "(Ljava/lang/String;Ljava/lang/Object;)Lp;");
    }

    static jobject _add(const jobject& obj, const jobject& arg0, const jobject& arg1) {
                
       const auto methodID = methodID__add();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID___add() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "setDetailError", "method_585", "add", "m_128162_"), "(Ljava/lang/String;Ljava/lang/Throwable;)V");
    }

    static void __add(const jobject& obj, const jobject& arg0, const jobject& arg1) {
                
       const auto methodID = methodID___add();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_initStackTrace() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "fillInStackTrace", "method_579", "initStackTrace", "m_128148_"), "(I)I");
    }

    static jint initStackTrace(const jobject& obj, const jint& arg0) {
                
       const auto methodID = methodID_initStackTrace();
       return MinecraftSDK::env->CallIntMethod(obj, methodID, arg0);
    };
    
    static jmethodID methodID_shouldGenerateStackTrace() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "validateStackTrace", "method_584", "shouldGenerateStackTrace", "m_128156_"), "(Ljava/lang/StackTraceElement;Ljava/lang/StackTraceElement;)Z");
    }

    static jboolean shouldGenerateStackTrace(const jobject& obj, const jobject& arg0, const jobject& arg1) {
                
       const auto methodID = methodID_shouldGenerateStackTrace();
       return MinecraftSDK::env->CallBooleanMethod(obj, methodID, arg0, arg1);
    };
    
    static jmethodID methodID_trimStackTraceEnd() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("b", "trimStacktrace", "method_580", "trimStackTraceEnd", "m_128174_"), "(I)V");
    }

    static void trimStackTraceEnd(const jobject& obj, const jint& arg0) {
                
       const auto methodID = methodID_trimStackTraceEnd();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0);
    };
    
    static jmethodID methodID_addStackTrace() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getDetails", "method_574", "addStackTrace", "m_128168_"), "(Ljava/lang/StringBuilder;)V");
    }

    static void addStackTrace(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_addStackTrace();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0);
    };
    
    static jmethodID methodID_getStackTrace() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "getStacktrace", "method_575", "getStackTrace", "m_128143_"), "()[Ljava/lang/StackTraceElement;");
    }

    static jobject getStackTrace(const jobject& obj) {
                
       const auto methodID = methodID_getStackTrace();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID);
    };
    
    static jmethodID methodID_addBlockInfo() {
       const auto clazz = self();
       return MinecraftSDK::env->GetStaticMethodID(clazz, MinecraftSDK::getRemapped("a", "populateBlockDetails", "method_586", "addBlockInfo", "m_178950_"), "(Lp;Ldcy;Ljd;Ldtc;)V");
    }

    static void addBlockInfo(const jobject& arg0, const jobject& arg1, const jobject& arg2, const jobject& arg3) {
       const auto clazz = self();
       const auto methodID = methodID_addBlockInfo();
       MinecraftSDK::env->CallStaticVoidMethod(clazz, methodID, arg0, arg1, arg2, arg3);
    };
    
};

#endif // NET_MINECRAFT_UTIL_CRASH_CRASHREPORTSECTION_HPP