// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_NETWORK_PACKET_S2C_COMMON_CUSTOMREPORTDETAILSS2CPACKET_HPP
#define NET_MINECRAFT_NETWORK_PACKET_S2C_COMMON_CUSTOMREPORTDETAILSS2CPACKET_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket
 * Remapped: zo
 */
namespace CustomReportDetailsS2CPacket {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("zo", "net/minecraft/network/protocol/common/ClientboundCustomReportDetailsPacket", "net/minecraft/class_9814", "net/minecraft/network/packet/s2c/common/CustomReportDetailsS2CPacket", "net/minecraft/src/C_336465_"));
        }
        return cachedClass;
    };

    // getter for private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#details
    static jobject get_field_details(const jobject &obj) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("b", "details", "comp_2858", "details", "f_337727_"), "Ljava/util/Map;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetObjectField(obj, fieldID);
    };

    // setter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#details
    static void set_field_details(const jobject &obj, const jobject &value) {
        const auto fieldID = MinecraftSDK::env->GetFieldID(self(), MinecraftSDK::getRemapped("b", "details", "comp_2858", "details", "f_337727_"), "Ljava/util/Map;");
        return MinecraftSDK::env->SetObjectField(obj, fieldID, value);
    };

    // getter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#MAX_KEY_LENGTH
    [[maybe_unused]] static jint get_field_MAX_KEY_LENGTH() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("c", "MAX_DETAIL_KEY_LENGTH", "field_52186", "MAX_KEY_LENGTH", "f_336809_"), "I");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticIntField(clazz, fieldID);
    };

    // setter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#MAX_KEY_LENGTH
    [[maybe_unused]] static void set_field_MAX_KEY_LENGTH(const jint &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("c", "MAX_DETAIL_KEY_LENGTH", "field_52186", "MAX_KEY_LENGTH", "f_336809_"), "I");
        return MinecraftSDK::env->SetStaticIntField(clazz, fieldID, value);
    };

    // getter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#MAX_VALUE_LENGTH
    [[maybe_unused]] static jint get_field_MAX_VALUE_LENGTH() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("d", "MAX_DETAIL_VALUE_LENGTH", "field_52187", "MAX_VALUE_LENGTH", "f_337666_"), "I");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticIntField(clazz, fieldID);
    };

    // setter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#MAX_VALUE_LENGTH
    [[maybe_unused]] static void set_field_MAX_VALUE_LENGTH(const jint &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("d", "MAX_DETAIL_VALUE_LENGTH", "field_52187", "MAX_VALUE_LENGTH", "f_337666_"), "I");
        return MinecraftSDK::env->SetStaticIntField(clazz, fieldID, value);
    };

    // getter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#MAX_DETAILS_SIZE
    [[maybe_unused]] static jint get_field_MAX_DETAILS_SIZE() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("e", "MAX_DETAIL_COUNT", "field_52188", "MAX_DETAILS_SIZE", "f_336623_"), "I");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticIntField(clazz, fieldID);
    };

    // setter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#MAX_DETAILS_SIZE
    [[maybe_unused]] static void set_field_MAX_DETAILS_SIZE(const jint &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("e", "MAX_DETAIL_COUNT", "field_52188", "MAX_DETAILS_SIZE", "f_336623_"), "I");
        return MinecraftSDK::env->SetStaticIntField(clazz, fieldID, value);
    };

    // getter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#DETAILS_CODEC
    [[maybe_unused]] static jobject get_field_DETAILS_CODEC() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("f", "DETAILS_STREAM_CODEC", "field_52189", "DETAILS_CODEC", "f_337354_"), "Lyx;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static private field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#DETAILS_CODEC
    [[maybe_unused]] static void set_field_DETAILS_CODEC(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("f", "DETAILS_STREAM_CODEC", "field_52189", "DETAILS_CODEC", "f_337354_"), "Lyx;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    // getter for static public field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#CODEC
    [[maybe_unused]] static jobject get_field_CODEC() {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("a", "STREAM_CODEC", "field_52185", "CODEC", "f_337359_"), "Lyx;");
        if(fieldID == nullptr) { return 0; }
        
        return MinecraftSDK::env->GetStaticObjectField(clazz, fieldID);
    };

    // setter for static public field net.minecraft.network.packet.s2c.common.CustomReportDetailsS2CPacket#CODEC
    [[maybe_unused]] static void set_field_CODEC(const jobject &value) {
        const auto clazz = self();
        const auto fieldID = MinecraftSDK::env->GetStaticFieldID(clazz, MinecraftSDK::getRemapped("a", "STREAM_CODEC", "field_52185", "CODEC", "f_337359_"), "Lyx;");
        return MinecraftSDK::env->SetStaticObjectField(clazz, fieldID, value);
    };

    static jmethodID methodID_getPacketId() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "type", "method_55846", "getPacketId", "m_5779_"), "()Lzi;");
    }

    static jobject getPacketId(const jobject& obj) {
                
       const auto methodID = methodID_getPacketId();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID);
    };
    
    static jmethodID methodID_apply() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "handle", "method_60929", "apply", "m_5797_"), "(Lzm;)V");
    }

    static void apply(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_apply();
       MinecraftSDK::env->CallVoidMethod(obj, methodID, arg0);
    };
    
    static jmethodID methodID__details() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("b", "details", "comp_2858", "details", "f_337727_"), "()Ljava/util/Map;");
    }

    static jobject _details(const jobject& obj) {
                
       const auto methodID = methodID__details();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID);
    };
    
};

#endif // NET_MINECRAFT_NETWORK_PACKET_S2C_COMMON_CUSTOMREPORTDETAILSS2CPACKET_HPP