// WARNING: This code was automatically generated by MinecraftCppSDK.
// It is highly recommended to not modify this file directly.
// Any changes made to this file will be overwritten by the next generation. 

#ifndef NET_MINECRAFT_SCREEN_SCREENHANDLERCONTEXT$2_HPP
#define NET_MINECRAFT_SCREEN_SCREENHANDLERCONTEXT$2_HPP
#include <sdk.hpp>


/*
 * Minecraft class
 * Original: net.minecraft.screen.ScreenHandlerContext$2
 * Remapped: cqg$2
 */
namespace ScreenHandlerContext$2 {
    static jclass self() {
        static jclass cachedClass = nullptr;
        if (cachedClass == nullptr) {
            cachedClass = MinecraftSDK::env->FindClass(MinecraftSDK::getRemapped("cqg$2", "net/minecraft/world/inventory/ContainerLevelAccess$2", "net/minecraft/class_3914$2", "net/minecraft/screen/ScreenHandlerContext$2", "net/minecraft/src/C_1247_$C_1249_"));
        }
        return cachedClass;
    };

    static jmethodID methodID_get() {
       const auto clazz = self();
       return MinecraftSDK::env->GetMethodID(clazz, MinecraftSDK::getRemapped("a", "evaluate", "method_17395", "get", "m_6721_"), "(Ljava/util/function/BiFunction;)Ljava/util/Optional;");
    }

    static jobject get(const jobject& obj, const jobject& arg0) {
                
       const auto methodID = methodID_get();
       return MinecraftSDK::env->CallObjectMethod(obj, methodID, arg0);
    };
    
};

#endif // NET_MINECRAFT_SCREEN_SCREENHANDLERCONTEXT$2_HPP